/** “Hello” in each translate target language (shown in the translate flyout). */
export const LANGUAGE_HELLOS: Record<string, string> = {
  English: 'Hello',
  Spanish: 'Hola',
  French: 'Bonjour',
  German: 'Hallo',
  Portuguese: 'Olá',
  Italian: 'Ciao',
  Dutch: 'Hallo',
  Russian: 'Привет',
  Polish: 'Cześć',
  Ukrainian: 'Привіт',
  Czech: 'Ahoj',
  Romanian: 'Salut',
  Hungarian: 'Szia',
  Swedish: 'Hej',
  Norwegian: 'Hei',
  Danish: 'Hej',
  Finnish: 'Hei',
  Greek: 'Γεια',
  Turkish: 'Merhaba',
  Arabic: 'مرحبا',
  Hebrew: 'שלום',
  Persian: 'سلام',
  Hindi: 'नमस्ते',
  Bengali: 'হ্যালো',
  Tamil: 'வணக்கம்',
  Telugu: 'హలో',
  Marathi: 'नमस्कार',
  Gujarati: 'નમસ્તે',
  Kannada: 'ನಮಸ್ಕಾರ',
  Malayalam: 'ഹലോ',
  Punjabi: 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ',
  Odia: 'ନମସ୍କାର',
  Assamese: 'নমস্কাৰ',
  Urdu: 'سلام',
  Sanskrit: 'नमस्ते',
  Nepali: 'नमस्ते',
  Sinhala: 'ආයුබෝවන්',
  'Chinese (Simplified)': '你好',
  'Chinese (Traditional)': '你好',
  Japanese: 'こんにちは',
  Korean: '안녕하세요',
  Vietnamese: 'Xin chào',
  Thai: 'สวัสดี',
  Indonesian: 'Halo',
  Malay: 'Hello',
  Filipino: 'Kumusta',
  Swahili: 'Habari',
  Afrikaans: 'Hallo',
  Catalan: 'Hola',
  Croatian: 'Bok',
  Serbian: 'Здраво',
  Slovak: 'Ahoj',
  Bulgarian: 'Здравей',
  Lithuanian: 'Labas',
  Latvian: 'Sveiki',
  Estonian: 'Tere',
}

export function helloForLanguage(value: string): string {
  return LANGUAGE_HELLOS[value] ?? 'Hello'
}
